name: Build Image

on:
  push:
    branches: ['master']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    env:
      YCR_REGISTRY_ID: ${{ vars.YCR_REGISTRY_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create key.json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "key.json"
          json: ${{ secrets.YCR_KEY_JSON }}

      - name: Docker login into Yandex Registry by key.json
        run: cat key.json | docker login --username json_key --password-stdin cr.yandex | rm key.json

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mongodump-s3-service:latest

      - name: Docker tag latest for Yandex Registry
        run: docker image tag mongodump-s3-service:latest cr.yandex/${YCR_REGISTRY_ID}/mongodump-s3-service:latest

      - name: Docker push latest to Yandex Registry
        if: github.event_name != 'pull_request'
        run: docker push cr.yandex/${YCR_REGISTRY_ID}/mongodump-s3-service:latest
